# Generated by Django 2.0 on 2018-06-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloComentario', models.CharField(max_length=50)),
                ('cuerpoComentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.IntegerField()),
                ('asiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filas', models.IntegerField()),
                ('asientosPorFila', models.IntegerField()),
                ('asientosUltimaFila', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comentarios',
        ),
        migrations.DeleteModel(
            name='Entradas',
        ),
        migrations.DeleteModel(
            name='Salas',
        ),
        migrations.DeleteModel(
            name='Visualizaciones',
        ),
        migrations.RenameModel(
            old_name='Peliculas',
            new_name='Pelicula',
        ),
        migrations.AddField(
            model_name='visualizacion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula'),
        ),
        migrations.AddField(
            model_name='visualizacion',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Sala'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='visualizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Visualizacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula'),
        ),
    ]
